name: deploy

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: psolisc
  IMAGE_NAME: rest_api

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build + push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}


  loadTest:
    name: Load Testing
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -g artillery
          npm install --save-dev artillery-plugin-ensure

      - name: Run container
        run: |
          docker run -d --name rest-api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Run Load Test
        run: |
          set -e  # Detiene el workflow si la prueba de carga falla.

          artillery run loadTest/basic.yaml || exit 1


  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install
      - run: npm run test


  codeScan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}   
      - name: Get SonarCloud status
        run: |
          echo "SONAR_STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN}}: https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} | jq -r '.projectStatus.status')" >> $GITHUB_ENV
          
      - name: Sonar Status
        run: echo ${{ env.SONAR_STATUS }}

      - name: Check Status
        if: ${{ env.SONAR_STATUS == 'ERROR' }}
        #run: exit 1
        run: echo "Problemas de seguridad encontrados..."

  SnykCode:
  name: Snyk image scan
  needs: build
  runs-on: ubuntu-latest
  steps:
  - name: Run Snyk to check Docker image for vulnerabilities
    uses: snyk/actions/docker@master
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest   
    continue-on-error: true   